apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmosdb-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: cosmosdb-issue-apis-svc
            port:
              number: 80
        path: /