apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmosdb-api-ingress
  namespace: apis
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /rapis(/|$)(.*)
        backend:
          service:
            name: cosmosdb-issue-readapis-svc
            port:
              number: 80
      - pathType: Prefix
        path: /wapis(/|$)(.*)
        backend:
          service:
            name: cosmosdb-issue-writeapis-svc
            port:
              number: 80