apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosmosdb-api-ingress
  namespace: apis
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /apis(/|$)(.*)
        backend:
          service:
            name: cosmosdb-issue-apis-svc
            port:
              number: 80
      - pathType: Prefix
        path: /vnext(/|$)(.*)
        backend:
          service:
            name: cosmosdb-issue-apis-vnext-svc
            port:
              number: 80