apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: ingress-nginx
  chart:
    git: https://github.com/mullis623/iPaaSGitOps
    path: gitops-config/charts/ingress-nginx
    ref: main
  values:
    controller:
      replicaCount: 2
      nodeSelector: 
        kubernetes.io/os: linux
      admissionWebhooks:
        patch:
          nodeSelector:
            kubernetes.io/os: linux
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: csi
  namespace: kube-system
spec:
  releaseName: csi
  chart:
    git: https://github.com/mullis623/iPaaSGitOps
    path: gitops-config/charts/csi-secrets-store-provider-azure
    ref: main
  values:
    secrets-store-csi-driver:
      syncSecret:
        enabled: true
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pod-identity
  namespace: podidentity
spec:
  releaseName: pod-identity
  chart:
    git: https://github.com/mullis623/iPaaSGitOps
    path: gitops-config/charts/aad-pod-identity
    ref: main