apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-ipaasdemokv
spec:
  provider: azure
  secretObjects:
    - secretName: cosmos-db-container-id
      type: Opaque
      data:
      - key: containerkey
        objectName: CosmosDBContainerId
    - secretName: cosmos-db-endpoint
      type: Opaque
      data:
      - key: endpointkey
        objectName: CosmosDBEndpoint
    - secretName: cosmos-db-id
      type: Opaque
      data:
      - key: dbkey
        objectName: CosmosDBId
    - secretName: cosmos-db-readonly-key
      type: Opaque
      data:
      - key: readonlykey
        objectName: CosmosDBReadOnlyKey
    - secretName: cosmos-db-write-key
      type: Opaque
      data:
      - key: writekey
        objectName: CosmosDBWriteKey 
  parameters:
    usePodIdentity: "true"                                                 # [OPTIONAL] if not provided, will default to "false". Set to "true" if using pod identities.
    useVMManagedIdentity: "false"                                           # [OPTIONAL] if not provided, will default to "false". Set to "true" if using managed identities.
    userAssignedIdentityID: "b46044d8-c613-46f6-b935-4b4f2d7c36d4"   # [OPTIONAL] If you're using managed identities, use the client id to specify which user-assigned managed identity to use. If the value is empty, it defaults to use the system-assigned identity on the VM
    keyvaultName: "ipaasdemokv"                                        # [REQUIRED] the name of the key vault
                                                                            #     az keyvault show --name contosoKeyVault5
                                                                            #     the preceding command will display the key vault metadata, which includes the subscription ID, resource group name, key vault 
    cloudName: ""                                                           # [OPTIONAL] if not provided, Azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: CosmosDBContainerId                                               # [REQUIRED] object name                                                                            
          objectType: secret                                                # [REQUIRED] object types: secret, key, or cert
          objectVersion: ""                                                 # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: CosmosDBEndpoint
          objectType: secret
          objectVersion: ""
        - |
          objectName: CosmosDBId
          objectType: secret
          objectVersion: ""
        - |
          objectName: CosmosDBReadOnlyKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: CosmosDBWriteKey
          objectType: secret
          objectVersion: ""
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                                                    # [REQUIRED] the tenant ID of the key vault